### PR TITLE
ENHANCMENT EmbedCodeBlock

### PR DESCRIPTION
**Pull request by muskie9**
Allows for implementing embed codes, usually javascript, in a block.

### CODE REVIEW

**Review by jsirish — COMMENTED** [review]
Code looks good. But, we do have an EmbedBlock, should we rename this to something else? IframeBlock maybe?

**Comment by muskie9** [comment]
We could update the name, I kept it generic cause in this case it's `<script>` and `<div>` that are embedded.

**Comment by muskie9** [comment]
ping #46

**Review by jsirish — APPROVED** [review]
looks good to me!

**Pull request merged**
